import qrcode from 'qrcode';
import type { RequireSome } from '@thermopylae/core.declarations/lib';
import type { AuthenticatorOptions } from '@otplib/core';
import { Authenticator } from '@otplib/core';
import { createDigest, createRandomBytes } from '@otplib/plugin-crypto';
import { keyDecoder, keyEncoder } from '@otplib/plugin-thirty-two';
import { createException, ErrorCodes } from '../../error';
import { SecretEncryptor } from '../../helpers/secret-encryptor';
import type { AuthenticationContext } from '../../types/contexts';
import type { AccountModel } from '../../types/models';
import type { SecretEncryptionOptions } from '../../helpers/secret-encryptor';
import type { TwoFactorAuthStrategy } from './interface';
import type { AuthenticationSessionRepositoryHolder } from '../../helpers/authentication-session-repository-holder';

interface OnTwoFactorEnabledHookResult {
	totpSecretQRImageUrl: string;
}

interface AccountWithTotpSecret extends AccountModel {
	totpSecret: string;
}

interface TotpTwoFactorAuthStrategyOptions {
	readonly totp: {
		secretLength: number;
		encryption: SecretEncryptionOptions | false;
		authenticator: Readonly<
			Omit<
				RequireSome<AuthenticatorOptions<string>, 'algorithm' | 'digits' | 'encoding' | 'step' | 'window'>,
				'createDigest' | 'createHmacKey' | 'digest' | 'epoch' | 'createRandomBytes' | 'keyEncoder' | 'keyDecoder'
			>
		>;
	};
	readonly serviceName: string;
}

class TotpTwoFactorAuthStrategy<Account extends AccountWithTotpSecret> implements TwoFactorAuthStrategy<Account> {
	private readonly authenticator: Authenticator;

	private readonly totpEncryptor: SecretEncryptor;

	private readonly totpSecretLength: number;

	private readonly serviceName: string;

	public constructor(options: TotpTwoFactorAuthStrategyOptions) {
		this.authenticator = new Authenticator({
			...options.totp.authenticator,
			createDigest,
			createRandomBytes,
			keyDecoder,
			keyEncoder
		});
		this.totpEncryptor = new SecretEncryptor(options.totp.encryption);
		this.totpSecretLength = options.totp.secretLength;
		this.serviceName = options.serviceName;
	}

	public async onTwoFactorAuthEnabled(account: Readonly<Account>, update: Partial<Account>): Promise<OnTwoFactorEnabledHookResult> {
		const totpSecret = this.authenticator.generateSecret(this.totpSecretLength);
		update.totpSecret = this.totpEncryptor.encrypt(totpSecret);

		const otpAuth = this.authenticator.keyuri(account.username, this.serviceName, totpSecret);
		return {
			totpSecretQRImageUrl: await qrcode.toDataURL(otpAuth)
		};
	}

	public async sendAuthenticationToken(
		account: AccountModel,
		_authenticationContext: AuthenticationContext,
		authenticationSessionRepositoryHolder: AuthenticationSessionRepositoryHolder
	): Promise<void> {
		const authenticationSession = await authenticationSessionRepositoryHolder.get();
		if (authenticationSession['2fa-token'] != null) {
			throw createException(
				ErrorCodes.TWO_FACTOR_AUTH_TOKEN_ISSUED_ALREADY,
				`Two factor authentication token was issued already for authentication session with id '${authenticationSessionRepositoryHolder.sessionId}' belonging to account with id '${account.id}'.`
			);
		}

		authenticationSession['2fa-token'] = 'totp-2fa-marker'; // just to enforce totp as second factor, and not to allow password bypass

		// we do not send any code, because it will be generated by user and sent to us
	}

	public async isAuthenticationTokenValid(
		account: Account,
		authenticationContext: AuthenticationContext,
		authenticationSessionRepositoryHolder: AuthenticationSessionRepositoryHolder
	): Promise<boolean> {
		const authenticationSession = await authenticationSessionRepositoryHolder.get();

		if (authenticationSession['2fa-token'] !== 'totp-2fa-marker') {
			return false;
		}

		if (this.authenticator.check(authenticationContext['2fa-token']!, this.totpEncryptor.decrypt(account.totpSecret))) {
			delete authenticationSession['2fa-token']; // prevent replay attacks
			return true;
		}

		return false;
	}
}

export { TotpTwoFactorAuthStrategy, TotpTwoFactorAuthStrategyOptions, AccountWithTotpSecret, OnTwoFactorEnabledHookResult };
