export const enum AccountRole {
	ADMIN = 'ADMIN',
	USER = 'USER'
}

export const enum LogoutType {
	CURRENT_SESSION = 'CURRENT_SESSION',
	ALL_SESSIONS = 'ALL_SESSIONS',
	ALL_SESSIONS_EXCEPT_CURRENT = 'ALL_SESSIONS_EXCEPT_CURRENT'
}
