/** The steps involved in authentication sequence */
const AUTH_STEP = {
	MFA: 'MFA',
	RESET_PASSWORD: 'RESET_PASSWORD',
	COMPLETED: 'COMPLETED'
};

/** The steps involved in the forgot password sequence */
const FORGOT_PASSWORD_STEP = {
	CREATE_SESSION: 'CREATE_SESSION',
	VERIFY_IDENTITY: 'VERIFY_IDENTITY',
	VERIFY_SECURITY_QUESTIONS: 'VERIFY_SECURITY_QUESTIONS',
	CHANGE_PASSWORD: 'CHANGE_PASSWORD'
};

/** The steps involved in the recover account sequence */
const RECOVER_ACCOUNT_STEP = {
	INIT: 'INIT',
	CHANGE_CREDENTIALS: 'CHANGE_CREDENTIALS'
};

const SECURITY_QUESTION_LANGUANGE = {
	EN: 'EN',
	RO: 'RO'
};

export { AUTH_STEP, FORGOT_PASSWORD_STEP, RECOVER_ACCOUNT_STEP, SECURITY_QUESTION_LANGUANGE };
