declare const enum Libraries {
	AUTH_ENGINE = 'AUTH_ENGINE_LIB',
	EMAIL = 'EMAIL_LIB',
	GEO_IP = 'GEO_IP_LIB',
	LOGGER = 'LOGGER_LIB',
	MEM_CACHE = 'MEM_CACHE_LIB',
	SMS = 'SMS_LIB',
	UTILS = 'UTILS_LIB'
}

declare const enum Services {
	AUTH = 'AUTH_SERVICE'
}

declare const enum AuthServiceMethods {
	AUTHENTICATE = 'AUTHENTICATE',
	ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT',
	ACTIVATE_MULTI_FACTOR_AUTHENTICATION = 'ACTIVATE_MULTI_FACTOR_AUTHENTICATION',
	CHANGE_FORGOTTEN_PASSWORD = 'CHANGE_FORGOTTEN_PASSWORD',
	CHANGE_PASSWORD = 'CHANGE_PASSWORD',
	CREATE_FORGOT_PASSWORD_SESSION = 'CREATE_FORGOT_PASSWORD_SESSION',
	GET_ACTIVE_SESSIONS = 'GET_ACTIVE_SESSIONS',
	GET_FAILED_AUTH_ATTEMPTS = 'GET_FAILED_AUTH_ATTEMPTS',
	LOCK_ACCOUNT = 'LOCK_ACCOUNT',
	LOGOUT = 'LOGOUT',
	LOGOUT_FROM_ALL_DEVICES = 'LOGOUT_FROM_ALL_DEVICES',
	LOGOUT_FROM_ALL_DEVICE_EXCEPT_FROM_CURRENT = 'LOGOUT_FROM_ALL_DEVICE_EXCEPT_FROM_CURRENT',
	REGISTER = 'REGISTER',
	UNLOCK_ACCOUNT = 'UNLOCK_ACCOUNT',
	VALIDATE_ACCOUNT_CREDENTIALS = 'VALIDATE_ACCOUNT_CREDENTIALS'
}

declare const enum AuthTokenType {
	BASIC = 'BASIC',
	OAUTH = 'OAUTH',
	GOOGLE = 'GOOGLE',
	FACEBOOK = 'FACEBOOK'
}

export { Libraries, AuthTokenType, Services, AuthServiceMethods };
