const SYSTEMS = {
	AUTH: 'AUTH_SYSTEM',
	EMAIL: 'EMAIL_SYSTEM',
	GEO_IP: 'GEO_IP',
	LOGGING: 'LOGGING_SYSTEM',
	MEM_CACHE: 'MEM_CACHE',
	SMS: 'SMS_SYSTEM',
	UTILS: 'UTILS'
};

const AUTH_TOKEN_TYPE = {
	BASIC: 'BASIC',
	OAUTH: 'OAUTH',
	GOOGLE: 'GOOGLE',
	FACEBOOK: 'FACEBOOK'
};

const OP_STATUS = {
	CREATED: 'CREATED',
	BEGIN: 'BEGIN',
	IN_PROGRESS: 'IN_PROGRESS',
	CANCELLED: 'CANCELLED',
	DONE: 'DONE',
	FAILED: 'FAILED'
};

const ACTIONS = {
	CREATE: 'CREATE',
	CREATE_BULK: 'CREATE_BULK',
	READ: 'READ',
	READ_BY_ID: 'READ_BY_ID',
	UPDATE: 'UPDATE',
	DELETE: 'DELETE',
	DELETE_BULK: 'DELETE_BULK',
	SCHEDULE: 'SCHEDULE'
};

const RESOURCES = {
	AUTH_SESSION: 'AUTH_SESSION',
	FORGOT_PASSWORD_SESSION: 'FORGOT_PASSWORD_SESSION',
	RESET_PASSWORD_SESSION: 'RESET_PASSWORD_SESSION',
	SESSION: 'SESSION'
};

export { SYSTEMS, AUTH_TOKEN_TYPE, OP_STATUS, ACTIONS, RESOURCES };
