enum SERVICES {
	AUTH = 'AUTH_SERVICE'
}

enum AUTH_SERVICE_METHODS {
	AUTHENTICATE = 'AUTHENTICATE'
}

const SERVICES_OPERATIONS = {
	[SERVICES.AUTH]: AUTH_SERVICE_METHODS
};

export { SERVICES, AUTH_SERVICE_METHODS, SERVICES_OPERATIONS };
