enum SERVICES {
	AUTH = 'AUTH_SERVICE'
}

enum AUTH_SERVICE_METHODS {
	AUTHENTICATE = 'AUTHENTICATE',
	REGISTER = 'REGISTER',
	ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT'
}

const SERVICES_OPERATIONS = {
	[SERVICES.AUTH]: AUTH_SERVICE_METHODS
};

export { SERVICES, AUTH_SERVICE_METHODS, SERVICES_OPERATIONS };
