export const enum ErrorCodes {
	API_ERROR = 'API_ERROR',
	BAD_INVARIANT = 'BAD_INVARIANT',
	CHECK_FAILED = 'CHECK_FAILED',
	DUPLICATE = 'DUPLICATE',
	EXISTS = 'EXISTS',
	EXPIRED = 'EXPIRED',
	FULL = 'FULL',
	INVALID = 'INVALID',
	MISCONFIGURATION = 'MISCONFIGURATION',
	NOT_ALLOWED = 'NOT_ALLOWED',
	NOT_FOUND = 'NOT_FOUND',
	NOT_EQUAL = 'NOT_EQUAL',
	NOT_AVAILABLE = 'NOT_AVAILABLE',
	NOT_CREATED = 'NOT_CREATED',
	OVERFLOW = 'OVERFLOW',
	REQUIRED = 'REQUIRED',
	UNKNOWN = 'UNKNOWN',
	UNPROCESSABLE = 'UNPROCESSABLE'
}

export const enum Library {
	ASYNC = 'LIB_ASYNC',
	AUTHENTICATION = 'LIB_AUTHENTICATION',
	CACHE = 'LIB_CACHE',
	INDEXED_STORE = 'LIB_INDEXED_STORE',
	COLLECTION = 'LIB_COLLECTION',
	HEAP = 'LIB_HEAP',
	GEO_IP = 'LIB_GEO_IP',
	JWT_USER_SESSION = 'LIB_JWT_USER_SESSION',
	LOGGER = 'LIB_LOGGER',
	POOL = 'LIB_POOL',
	SMS_CLIENT = 'LIB_SMS_CLIENT',
	UNIT_TEST = 'LIB_UNIT_TEST',
	USER_SESSION = 'LIB_USER_SESSION',
	UTILS = 'LIB_UTILS'
}

export const enum CoreModule {
	USER_SESSION_COMMONS = 'CORE_USER_SESSION',
	JWT_USER_SESSION = 'CORE_JWT_SESSION',
	COOKIE_USER_SESSION = 'CORE_COOKIE_SESSION'
}

export const enum Client {
	SMS = 'SMS_CLIENT',
	EMAIL = 'EMAIL_CLIENT',
	REDIS = 'REDIS_CLIENT',
	MYSQL = 'MYSQL_CLIENT'
}

export const enum AuthTokenType {
	BASIC = 'BASIC',
	OAUTH = 'OAUTH',
	GOOGLE = 'GOOGLE',
	FACEBOOK = 'FACEBOOK'
}

export const enum StatusFlag {
	ENABLED,
	DISABLED,
	IDLE
}

export const enum SortDirection {
	ASCENDING,
	DESCENDING
}

export const enum ComparisonResult {
	GREATER = 1,
	EQUALS = 0,
	SMALLER = -1
}

export const enum ConcurrencyType {
	SEQUENTIAL,
	PARALLEL,
	BATCH
}
