enum AUTH_STEP {
	DISPATCH = 'DISPATCH',
	SECRET = 'SECRET',
	GENERATE_TOTP = 'GENERATE_TOTP',
	TOTP = 'TOTP',
	PUBKEY = 'PUBKEY',
	RECAPTCHA = 'RECAPTCHA',
	AUTHENTICATED = 'AUTHENTICATED',
	ERROR = 'ERROR'
}

export { AUTH_STEP };
