enum AUTH_STEP {
	DISPATCH = 'DISPATCH',
	PASSWORD = 'PASSWORD',
	GENERATE_TOTP = 'GENERATE_TOTP',
	TOTP = 'TOTP',
	GENERATE_CHALLENGE = 'GENERATE_CHALLENGE',
	CHALLENGE_RESPONSE = 'CHALLENGE_RESPONSE',
	RECAPTCHA = 'RECAPTCHA',
	AUTHENTICATED = 'AUTHENTICATED',
	ERROR = 'ERROR',
	UNKNOWN = 'UNKNOWN'
}

export { AUTH_STEP };
