export const enum Services {
	AUTH = 'AUTH_SERVICE'
}

export const enum AuthServiceMethods {
	AUTHENTICATE = 'AUTHENTICATE',
	ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT',
	CHANGE_ACCOUNT_STATUS = 'CHANGE_ACCOUNT_STATUS',
	CHANGE_FORGOTTEN_PASSWORD = 'CHANGE_FORGOTTEN_PASSWORD',
	CHANGE_PASSWORD = 'CHANGE_PASSWORD',
	CREATE_FORGOT_PASSWORD_SESSION = 'CREATE_FORGOT_PASSWORD_SESSION',
	CHANGE_MULTI_FACTOR_AUTHENTICATION_STATUS = 'CHANGE_MULTI_FACTOR_AUTHENTICATION_STATUS',
	GET_ACTIVE_SESSIONS = 'GET_ACTIVE_SESSIONS',
	GET_FAILED_AUTH_ATTEMPTS = 'GET_FAILED_AUTH_ATTEMPTS',
	LOGOUT = 'LOGOUT',
	LOGOUT_FROM_ALL_DEVICES = 'LOGOUT_FROM_ALL_DEVICES',
	LOGOUT_FROM_ALL_DEVICE_EXCEPT_FROM_CURRENT = 'LOGOUT_FROM_ALL_DEVICE_EXCEPT_FROM_CURRENT',
	REGISTER = 'REGISTER',
	VALIDATE_ACCOUNT_CREDENTIALS = 'VALIDATE_ACCOUNT_CREDENTIALS'
}

