export const enum Services {
	AUTH = 'AUTH_SERVICE'
}

export const enum AuthServiceMethods {
	AUTHENTICATE = 'AUTHENTICATE',
	ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT',
	ACTIVATE_MULTI_FACTOR_AUTHENTICATION = 'ACTIVATE_MULTI_FACTOR_AUTHENTICATION',
	CHANGE_FORGOTTEN_PASSWORD = 'CHANGE_FORGOTTEN_PASSWORD',
	CHANGE_PASSWORD = 'CHANGE_PASSWORD',
	CREATE_FORGOT_PASSWORD_SESSION = 'CREATE_FORGOT_PASSWORD_SESSION',
	GET_ACTIVE_SESSIONS = 'GET_ACTIVE_SESSIONS',
	GET_FAILED_AUTH_ATTEMPTS = 'GET_FAILED_AUTH_ATTEMPTS',
	LOCK_ACCOUNT = 'LOCK_ACCOUNT',
	LOGOUT = 'LOGOUT',
	LOGOUT_FROM_ALL_DEVICES = 'LOGOUT_FROM_ALL_DEVICES',
	LOGOUT_FROM_ALL_DEVICE_EXCEPT_FROM_CURRENT = 'LOGOUT_FROM_ALL_DEVICE_EXCEPT_FROM_CURRENT',
	REGISTER = 'REGISTER',
	UNLOCK_ACCOUNT = 'UNLOCK_ACCOUNT',
	VALIDATE_ACCOUNT_CREDENTIALS = 'VALIDATE_ACCOUNT_CREDENTIALS'
}

