export const enum AuthenticationStepName {
	DISPATCH = 'DISPATCH',
	PASSWORD = 'PASSWORD',
	GENERATE_2FA_TOKEN = 'GENERATE_2FA_TOKEN',
	TWO_FACTOR_AUTH_CHECK = 'TWO_FACTOR_AUTH_CHECK',
	GENERATE_CHALLENGE = 'GENERATE_CHALLENGE',
	CHALLENGE_RESPONSE = 'CHALLENGE_RESPONSE',
	RECAPTCHA = 'RECAPTCHA',
	AUTHENTICATED = 'AUTHENTICATED',
	ERROR = 'ERROR',
	UNKNOWN = 'UNKNOWN'
}

export const enum TwoFactorAuthAChannelType {
	EMAIL,
	SMS,
	TOTP,
	PUSH_NOTIFICATION
}

export const enum TwoFactorAuthOperationType {
	DISABLED = 0,
	AUTHENTICATION = 1 << 0,
	CHANGE_PASSWORD = 1 << 1,
	VERIFY_CREDENTIALS = 1 << 2
}
