export const enum AUTH_STEP {
	DISPATCH = 'DISPATCH',
	PASSWORD = 'PASSWORD',
	GENERATE_TOTP = 'GENERATE_TOTP',
	TOTP = 'TOTP',
	GENERATE_CHALLENGE = 'GENERATE_CHALLENGE',
	CHALLENGE_RESPONSE = 'CHALLENGE_RESPONSE',
	RECAPTCHA = 'RECAPTCHA',
	AUTHENTICATED = 'AUTHENTICATED',
	ERROR = 'ERROR',
	UNKNOWN = 'UNKNOWN'
}

export const enum MFAOperation {
	DISABLED = 0,
	AUTHENTICATION = 1 << 0,
	CHANGE_PASSWORD = 1 << 1,
	VERIFY_CREDENTIALS = 1 << 2
}
