export const enum AuthenticationStepName {
	DISPATCH = 'DISPATCH',
	PASSWORD = 'PASSWORD',
	GENERATE_2FA_TOKEN = 'GENERATE_2FA_TOKEN',
	TWO_FACTOR_AUTH_CHECK = 'TWO_FACTOR_AUTH_CHECK',
	GENERATE_CHALLENGE = 'GENERATE_CHALLENGE',
	CHALLENGE_RESPONSE = 'CHALLENGE_RESPONSE',
	RECAPTCHA = 'RECAPTCHA',
	AUTHENTICATED = 'AUTHENTICATED',
	ERROR = 'ERROR',
	UNKNOWN = 'UNKNOWN'
}

export const enum AccountStatus {
	ENABLED = 0,
	DISABLED_UNTIL_ACTIVATION = -1
}
